üóìÔ∏è Data: 27/09/2025

`try` tenta executar determinado c√≥digo, caso ocorra qualquer erro (com exce√ß√£o de syntax) ele vai capturar o erro com `except` e fazer o que estiver dentro do bloco de c√≥digo

Imagine que queiramos converter uma string para um n√∫mero inteiro, o que n√£o faz nenhum sentido. `int()` e `float()` converte somente n√∫meros, float para int e int para float. Tentar converter uma string com `int("a")` ou `float("a")`claramente geraria um erro, mas n√£o de syntax, e sim um erro de execu√ß√£o

```python
try:
    numero = int("a")
except:
    print("Ocorreu um erro") # Sa√≠da: Ocorreu um erro
```

O que o `try` est√° tentando fazer, √© **TENTAR** executar o bloco de c√≥digo dele, e caso **QUALQUER** erro seja capturado, ele vai executar o bloco `except`

###